version: '3.4'
services: 
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes: 
            - .:/usr/app
            - /usr/app/node_modules
        ports: 
            - "80:8080"
        depends_on: 
            - db
        links: 
            - db
        environment: 
            GOOGLE_APPLICATION_CREDENTIALS: estudos-cloud-274013-51cd867a7e80.json
            GCLOUD_PROJECT: estudos-cloud-274013
    db:
        image:  mysql:5.6
        ports: 
            - "3306:3306"
        restart: always
        volumes:
            - ./data:/var/lib/mysql
        expose: 
            - 3306
        environment: 
            MYSQL_ROOT_PASSWORD: admin123
            MYSQL_DATABASE: dbsgram